


name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node_version}}
    - name: Install dependencies
      run: npm install
    - name: Super-Linter        
      uses: super-linter/super-linter@v6.7.0
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main


